version: '3.4'

services:
  onlinetheatredb:
    image: mcr.microsoft.com/mssql/server
    
  OnlineTheatreApi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
